export const SETUP = {
  CHOOSE_NAME: 'CHOOSE_NAME',
  RESET: 'RESET',
};

export const GAME = {
  NEW_MOVE: 'NEW_MOVE',
  RESET_BOARD: 'RESET_BOARD',
  SET_WINNING_PATH: 'SET_WINNING_PATH',
  SET_DRAW: 'SET_DRAW',
  SET_DIMENSION: 'SET_DIMENSION',
  JOIN_GAME: 'JOIN_GAME',
  GAME_JOINED: 'GAME_JOINED',
  CONNECTED: 'CONNECTED',
  PEER_READY: 'PEER_READY',
  PEER_MOVE: 'PEER_MOVE',
};
