export const DUMMY = {
  LOAD_DUMMIES: 'LOAD_DUMMIES',
  SAVE_DUMMY: 'SAVE_DUMMY',
  DELETE_DUMMY: 'DELETE_DUMMY',
  NEW_DUMMY: 'NEW_DUMMY',
};

export const SETUP = {
  CHOOSE_NAME: 'CHOOSE_NAME',
  RESET: 'RESET',
};

export const GAME = {
  NEW_MOVE: 'NEW_MOVE',
  RESET_BOARD: 'RESET_BOARD',
};
